site_name: Acahelp Docs
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  extra_css:
    - 'stylesheets/extra.css'
  font:
    text: Muli
  palette:
    primary: white
    accent: light blue
  features:
    - navigation.top
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
  plugins:
    - search
  markdown_extensions:
    - toc:
        permalink: "#"
    - tables
    - attr_list
