site_name: Acahelp Docs
theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - navigation.sections
  plugins:
    - search
  nav:
    - 'Acahelp Docs': index.md
    - 'Member Account':
        Getting started as a member: member/index.md
