site_name: Acahelp Docs
theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - navigation.sections
    - navigation.indexes
  plugins:
    - search
  nav:
    - Getting Started:
        - 'index.md'
    - Member Account:
        - Getting started as a member: 'member/index.md'
