site_name: Acahelp Docs
theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - navigation.sections
  plugins:
    - search
  nav:
    - index.md
    - customizing.md
    - Countdown Timer.md
    - support.md
