site_name: Acahelp Docs
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  extra_css:
    - 'stylesheets/extra.css'
  font:
    text: Muli
  palette:
    primary: white
    accent: light blue
  features:
    - navigation.top
    - search.suggest
    - navigation.sections
    - navigation.indexes
  plugins:
    - search
  markdown_extensions:
    - toc:
        permalink: "#"
    - tables
  nav:
    - Getting Started:
        - 'index.md'
    - Member Account:
        - Getting started as a member: 'member/index.md'
